### ISSUE TITLE
Good feature

### ISSUE THREAD

**Issue by Skyexir** [MrAmericanMike/RemoveMouseoverHighlight#1]
Hello sir

Would it be possible to make a version of the mod that removes the outlier only on invisible blocks (barrier block)
It would be very useful for me (maybe for others too)

Have a good day !

**Comment by MrAmericanMike** [comment]
I haven't been updating my mods in a while, but I guess I could take a look at adding that feature as a config option.

**Comment by MrAmericanMike** [comment]
Posted this today as version 1.0.1 for Minecraft 1.20.x https://legacy.curseforge.com/minecraft/mc-mods/remove-mouseover-highlight

Hopefully it does what you want. In the future I may add more control over this kind of behavior for other special blocks.
